# Generated by Django 4.1 on 2022-08-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('price', models.TextField()),
                ('quantity', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
