# Generated by Django 4.1 on 2022-08-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPSapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='item',
            new_name='model',
        ),
        migrations.AddField(
            model_name='data',
            name='brand',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='vendor',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
    ]
