# Generated by Django 4.1 on 2022-08-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPSapp', '0002_rename_item_data_model_data_brand_data_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='brand',
            field=models.TextField(),
        ),
    ]
